name: SauceDemo Katalon CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Katalon Studio
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v9.1.0/Katalon_Studio_Linux_9.1.0.tar.gz
          tar -xzf Katalon_Studio_Linux_9.1.0.tar.gz

      - name: Run Katalon Test Suite
        run: |
          ./Katalon_Studio_Linux_9.1.0/katalonc \
            -noSplash \
            -runMode=console \
            -projectPath="$(pwd)" \
            -testSuitePath="Test Suites/SmokeSuite" \
            -executionProfile="default" \
            -browserType="Chrome"

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: katalon-reports
          path: Reports/

